-- =====================================================
-- ELIMS DATABASE SCHEMA
-- Idempotent, PostgreSQL 10+ (IDENTITY instead of SERIAL)
-- =====================================================

-- Enable extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =====================================================
-- ENUM TYPES
-- =====================================================

DO $$
BEGIN
    CREATE TYPE public.patient_gender AS ENUM ('Male', 'Female', 'Other', 'Unknown');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE public.marital_status_enum AS ENUM ('Single', 'Married', 'Divorced', 'Widowed', 'Other');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE public.admission_type_enum AS ENUM ('OPD', 'IPD', 'Emergency');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE public.test_request_status AS ENUM ('Pending', 'SampleCollected', 'InProgress', 'Completed', 'Verified', 'Cancelled');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE public.payment_status_enum AS ENUM ('Paid', 'Unpaid', 'Partial');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE public.test_item_status AS ENUM ('Pending', 'InProgress', 'Completed', 'Verified', 'Rejected');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE public.invoice_status AS ENUM ('pending', 'paid', 'cancelled');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE public.gender_enum AS ENUM ('Any', 'Male', 'Female');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE public.range_type_enum AS ENUM ('numeric', 'qualitative');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE public.ingest_status AS ENUM ('queued', 'processed', 'failed', 'reprocessing');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- =====================================================
-- CORE TABLES
-- =====================================================

CREATE TABLE IF NOT EXISTS public.roles (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL UNIQUE,
    description TEXT,
    core        BOOLEAN DEFAULT false,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.permissions (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150) NOT NULL,
    code        VARCHAR(100) UNIQUE NOT NULL,
    resource    TEXT NOT NULL,
    action      TEXT NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.departments (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) UNIQUE NOT NULL,
    is_active  BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.wards (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.units (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol      VARCHAR(20) UNIQUE,
    unit_name   VARCHAR(100),
    description VARCHAR(100),
    is_active   BOOLEAN DEFAULT true,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.sample_types (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL UNIQUE,
    container_type VARCHAR(100),
    description   TEXT,
    is_active     BOOLEAN DEFAULT true,
    created_at    TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.users (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name        VARCHAR(255) NOT NULL,
    email            VARCHAR(255) NOT NULL UNIQUE,
    password_hash    TEXT NOT NULL,
    department_id    INTEGER,
    role_id          INTEGER,
    department       VARCHAR(100),        -- 👈 for backward-compatible login
    profile_image_url TEXT,
    is_active        BOOLEAN DEFAULT true,
    last_login_at    TIMESTAMPTZ,
    last_seen        TIMESTAMPTZ,
    created_at       TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_users_department
        FOREIGN KEY (department_id) REFERENCES public.departments(id) ON DELETE SET NULL
);

-- Make sure dept + role columns exist on older DBs
ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS department_id INTEGER,
    ADD COLUMN IF NOT EXISTS role_id INTEGER,
    ADD COLUMN IF NOT EXISTS department VARCHAR(100);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_users_department'
    ) THEN
        ALTER TABLE public.users
            ADD CONSTRAINT fk_users_department
            FOREIGN KEY (department_id) REFERENCES public.departments(id) ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_users_role'
    ) THEN
        ALTER TABLE public.users
            ADD CONSTRAINT fk_users_role
            FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.user_roles (
    user_id INTEGER REFERENCES public.users(id) ON DELETE CASCADE,
    role_id INTEGER REFERENCES public.roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS public.role_permissions (
    role_id       INTEGER REFERENCES public.roles(id) ON DELETE CASCADE,
    permission_id INTEGER REFERENCES public.permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INTEGER,
    action     VARCHAR(255) NOT NULL,
    details    JSONB,
    entity     VARCHAR(100),
    entity_id  INTEGER,
    entity_type VARCHAR(50),
    user_name  TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_audit_user
        FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL
);

-- =====================================================
-- MRN SETTINGS
-- =====================================================

CREATE TABLE IF NOT EXISTS public.mrn_settings (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_code VARCHAR(10) NOT NULL DEFAULT 'MTD',
    reset_yearly  BOOLEAN NOT NULL DEFAULT true,
    last_sequence INTEGER NOT NULL DEFAULT 0,
    updated_at    TIMESTAMPTZ DEFAULT NOW()
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_facility_code') THEN
        ALTER TABLE public.mrn_settings
            ADD CONSTRAINT unique_facility_code UNIQUE (facility_code);
    END IF;
END $$;

-- =====================================================
-- PATIENTS
-- =====================================================

CREATE TABLE IF NOT EXISTS public.patients (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mrn                    VARCHAR(50) UNIQUE,
    first_name             VARCHAR(255) NOT NULL,
    middle_name            VARCHAR(255),
    last_name              VARCHAR(255) NOT NULL,
    date_of_birth          DATE NOT NULL,
    gender                 public.patient_gender,
    marital_status         public.marital_status_enum,
    occupation             VARCHAR(255),
    contact_phone          VARCHAR(50),
    contact_address        TEXT,
    contact_email          VARCHAR(255),
    admission_type         public.admission_type_enum DEFAULT 'OPD',
    lab_id                 VARCHAR(50) UNIQUE,
    ward_id                INTEGER REFERENCES public.wards(id) ON DELETE SET NULL,
    referring_doctor       VARCHAR(255),
    emergency_name         VARCHAR(255),
    emergency_relationship VARCHAR(100),
    emergency_phone        VARCHAR(50),
    registered_by          INTEGER REFERENCES public.users(id) ON DELETE SET NULL,
    registered_at          TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- TEST CATALOG + PANELS
-- =====================================================

CREATE TABLE IF NOT EXISTS public.test_catalog (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL UNIQUE,
    code           VARCHAR(50) UNIQUE,
    price          NUMERIC(10,2) NOT NULL DEFAULT 0,
    department_id  INTEGER REFERENCES public.departments(id) ON DELETE SET NULL,
    sample_type_id INTEGER REFERENCES public.sample_types(id) ON DELETE SET NULL,
    unit_id        INTEGER REFERENCES public.units(id) ON DELETE SET NULL,
    is_panel       BOOLEAN DEFAULT false,
    is_active      BOOLEAN DEFAULT true,
    result_value   TEXT,
    created_at     TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.test_panel_analytes (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    panel_id   INTEGER REFERENCES public.test_catalog(id) ON DELETE CASCADE,
    analyte_id INTEGER REFERENCES public.test_catalog(id) ON DELETE CASCADE,
    analyte_name TEXT
);

-- =====================================================
-- TEST REQUESTS & ITEMS
-- =====================================================

CREATE TABLE IF NOT EXISTS public.test_requests (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id          INTEGER REFERENCES public.patients(id) ON DELETE RESTRICT,
    created_at          TIMESTAMPTZ DEFAULT NOW(),
    status              public.test_request_status DEFAULT 'Pending',
    doctor_id           INTEGER REFERENCES public.users(id) ON DELETE SET NULL,
    sample_collected_at TIMESTAMPTZ,
    collected_by        INTEGER REFERENCES public.users(id) ON DELETE SET NULL,
    payment_status      public.payment_status_enum DEFAULT 'Unpaid',
    updated_at          TIMESTAMPTZ DEFAULT NOW(),
    external_sample_id  VARCHAR(64),
    created_by          INTEGER REFERENCES public.users(id) ON DELETE SET NULL,
    payment_amount      NUMERIC(14,2),
    payment_method      TEXT,
    payment_date        TIMESTAMPTZ,
    ward_id             INTEGER REFERENCES public.wards(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.test_request_items (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_request_id INTEGER NOT NULL REFERENCES public.test_requests(id) ON DELETE CASCADE,
    test_catalog_id INTEGER NOT NULL REFERENCES public.test_catalog(id) ON DELETE RESTRICT,
    result_value    TEXT,
    result_data     JSONB,
    status          public.test_item_status DEFAULT 'Pending',
    parent_id       INTEGER REFERENCES public.test_request_items(id) ON DELETE CASCADE,
    verified_by     INTEGER REFERENCES public.users(id) ON DELETE SET NULL,
    verified_name   VARCHAR(255),
    verified_at     TIMESTAMPTZ,
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- BILLING / INVOICES
-- =====================================================

CREATE TABLE IF NOT EXISTS public.invoices (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id     INTEGER REFERENCES public.patients(id) ON DELETE SET NULL,
    test_request_id INTEGER REFERENCES public.test_requests(id) ON DELETE SET NULL,
    amount         NUMERIC(10, 2) NOT NULL,
    status         public.invoice_status DEFAULT 'pending',
    due_date       DATE,
    created_at     TIMESTAMPTZ DEFAULT NOW(),
    updated_at     TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- NORMAL RANGES
-- =====================================================

CREATE TABLE IF NOT EXISTS public.normal_ranges (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analyte_id           INTEGER REFERENCES public.test_catalog(id) ON DELETE CASCADE,
    gender               public.gender_enum DEFAULT 'Any',
    range_type           public.range_type_enum DEFAULT 'numeric',
    qualitative_value    VARCHAR(50),
    symbol_operator      VARCHAR(10),
    age_min              NUMERIC,
    age_max              NUMERIC,
    unit_id              INTEGER REFERENCES public.units(id) ON DELETE SET NULL,
    min_value            NUMERIC,
    max_value            NUMERIC,
    reference_range_text TEXT,
    min_age              INTEGER,
    max_age              INTEGER
);

-- =====================================================
-- API KEYS
-- =====================================================

CREATE TABLE IF NOT EXISTS public.api_keys (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INTEGER NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    name         VARCHAR(255) NOT NULL,
    key_prefix   VARCHAR(32) NOT NULL,
    key_hash     TEXT NOT NULL,
    secret_hash  TEXT,
    salt         VARCHAR(64),
    created_at   TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMPTZ,
    revoked_at   TIMESTAMPTZ,
    UNIQUE (key_prefix)
);

-- =====================================================
-- INSTRUMENT INGEST EVENTS
-- =====================================================

CREATE TABLE IF NOT EXISTS public.instrument_ingest_events (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_id      INTEGER REFERENCES public.api_keys(id) ON DELETE SET NULL,
    user_id     INTEGER REFERENCES public.users(id) ON DELETE SET NULL,
    instrument  VARCHAR(100) NOT NULL,
    sample_id   VARCHAR(100) NOT NULL,
    payload     JSONB NOT NULL,
    status      public.ingest_status NOT NULL DEFAULT 'queued',
    error_msg   TEXT,
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    processed_at TIMESTAMPTZ
);

-- =====================================================
-- SYSTEM SETTINGS
-- =====================================================

CREATE TABLE IF NOT EXISTS public.system_settings (
    key        TEXT PRIMARY KEY,
    value      TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- INDEXES
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_patients_mrn
    ON public.patients (mrn);

CREATE INDEX IF NOT EXISTS idx_patients_name
    ON public.patients (first_name, last_name);

CREATE INDEX IF NOT EXISTS idx_test_requests_patient
    ON public.test_requests (patient_id);

CREATE INDEX IF NOT EXISTS idx_test_requests_status
    ON public.test_requests (status);

CREATE INDEX IF NOT EXISTS idx_test_request_items_request
    ON public.test_request_items (test_request_id);

CREATE INDEX IF NOT EXISTS idx_audit_logs_user
    ON public.audit_logs (user_id);

-- =====================================================
-- SEED DATA (IDEMPOTENT)
-- =====================================================

DO $$
DECLARE
    superadmin_role_id INTEGER;
    admin_dept_id      INTEGER;
BEGIN
    -- Departments
    INSERT INTO public.departments (name, is_active)
    VALUES
        ('Administration', true),
        ('Chemistry', true),
        ('Hematology', true),
        ('Microbiology', true)
    ON CONFLICT (name) DO NOTHING;

    -- Roles
    INSERT INTO public.roles (name, core)
    VALUES ('SuperAdmin', true)
    ON CONFLICT (name) DO NOTHING;

    -- Get IDs
    SELECT id INTO superadmin_role_id FROM public.roles WHERE name = 'SuperAdmin';
    SELECT id INTO admin_dept_id FROM public.departments WHERE name = 'Administration';

    -- Super Admin User
    INSERT INTO public.users (
        full_name,
        email,
        password_hash,
        department_id,
        role_id,
        department,
        is_active,
        created_at
    )
    VALUES (
        'Super Admin',
        'admin@elims.local',
        '$2b$10$ndGozr07mi4aw4BPVbhjmurzrNxOYyBkFw8UdxbbYo1/MWVM/s1Qy',
        admin_dept_id,
        superadmin_role_id,
        'Administration',
        true,
        NOW()
    )
    ON CONFLICT (email) DO UPDATE SET
        full_name     = EXCLUDED.full_name,
        department_id = EXCLUDED.department_id,
        role_id       = EXCLUDED.role_id,
        department    = EXCLUDED.department;

    -- Link User → Role (for multi-role support)
    INSERT INTO public.user_roles (user_id, role_id)
    SELECT u.id, superadmin_role_id
    FROM public.users u
    WHERE u.email = 'admin@elims.local'
      AND NOT EXISTS (
          SELECT 1 FROM public.user_roles ur
          WHERE ur.user_id = u.id
            AND ur.role_id = superadmin_role_id
      );

    -- Sample Types
    INSERT INTO public.sample_types (name, description)
    VALUES
        ('Serum',  'Standard serum sample'),
        ('Plasma', 'Plasma sample'),
        ('Urine',  'Urine sample')
    ON CONFLICT (name) DO NOTHING;

    -- MRN Settings
    INSERT INTO public.mrn_settings (facility_code, reset_yearly, last_sequence)
    SELECT 'MTD', true, 0
    WHERE NOT EXISTS (
        SELECT 1 FROM public.mrn_settings WHERE facility_code = 'MTD'
    );

    -- Permissions
    INSERT INTO public.permissions (name, code, resource, action)
    VALUES
        ('View Patients',        'patients.view',        'patients',    'view'),
        ('Create Patient',       'patients.create',      'patients',    'create'),
        ('Update Patient',       'patients.update',      'patients',    'update'),
        ('View Tests',           'tests.view',           'tests',       'view'),
        ('Create Test',          'tests.create',         'tests',       'create'),
        ('Enter Results',        'results.enter',        'results',     'enter'),
        ('Verify Results',       'results.verify',       'results',     'verify'),
        ('View Reports',         'reports.view',         'reports',     'view'),
        ('Manage Inventory',     'inventory.view',       'inventory',   'view'),
        ('View Settings',        'settings.view',        'settings',    'view'),
        ('Edit Settings',        'settings.edit',        'settings',    'edit'),
        ('Phlebotomy Access',    'phlebotomy.view',      'phlebotomy',  'view'),
        ('Pathologist Access',   'pathologist.view',     'pathologist', 'view')
    ON CONFLICT (code) DO NOTHING;

    -- Grant ALL permissions to SuperAdmin
    INSERT INTO public.role_permissions (role_id, permission_id)
    SELECT superadmin_role_id, p.id
    FROM public.permissions p
    WHERE NOT EXISTS (
        SELECT 1 FROM public.role_permissions rp
        WHERE rp.role_id = superadmin_role_id
          AND rp.permission_id = p.id
    );
END $$;
